name: cleanup caches by branch
on:
  pull_request:
    types:
      - synchronize
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:       
      - name: Install Github Action Cache Manager
        run: gh extension install actions/gh-actions-cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current merge
        run: echo "value=refs/pull/${{ github.event.pull_request.number }}/merge"	>> $GITHUB_OUTPUT
        env:
          BRANCH: ${{ github.event.pull_request.base.ref }}
        id: merge

      - name: Fetching list of cache key
        run: |
          cacheKeysForPR=$(gh actions-cache list -R ${{ github.repository }} -B ${{ steps.merge.outputs.value }} | cut -f 1 )
          set +e
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
  
      - name: Deleting caches
        run: |
          for cacheKey in $cacheKeysForPR
          do
            gh actions-cache delete $cacheKey -R ${{ github.repository }} -B ${{ steps.merge.outputs.value }} --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}