name: "Main Tests & Analysis"

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/api/*' 
      - 'src/api/**'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'src/api/*' 
      - 'src/api/**'

permissions:
  checks: write
  pull-requests: write

jobs: 
  tests:
    name: Tests
    uses: ./.github/workflows/matrix_test_result.yml
    secrets: inherit
    with:
      dir: ./src/api/
      dotnet-version: 6.0.x

  code_analysis:
    name: Code Analysis
    needs: tests
    uses: ./.github/workflows/coverage_report.yml
    secrets: inherit
    with:
      dir: ./src/api/
      dotnet-version: 6.0.x